---
- name: Check webserver availability
  hosts: all
  sources:
    - ansible.eda.url_check:
        urls:
          - http://192.168.122.1:8080
        delay: 10

  rules:
    - name: Site is down
      condition: event.url_check.status == "down"
      action:
        debug:
          msg: "DOWN: {{ event.url_check.url }}"
    - name: General Infor
      condition: event.url_check.status == "down"
      action:
        debug:
          msg: "DOWN: {{ event }}"
...
